package by.pvt.module3.command.client;

public enum CommandEnum {
    LOGIN,
    LOGOUT,
    SEL_AIRPORT,
    INS_AIRPORT,
    UPD_AIRPORT,
    DEL_AIRPORT,
    SEL_AIRLINE,
    INS_AIRLINE,
    UPD_AIRLINE,
    DEL_AIRLINE,
    SEL_USER,
    INS_USER,
    UPD_USER,
    DEL_USER,
    SEL_STAFF,
    INS_STAFF,
    UPD_STAFF,
    DEL_STAFF,
    SEL_FLIGHT,
    INS_FLIGHT,
    UPD_FLIGHT,
    DEL_FLIGHT,
    SEL_CREW,
    INS_CREW,
    UPD_CREW,
    DEL_CREW,
    INS_MEMBER,
    DEL_MEMBER;
}